#!/bin/sh /etc/rc.common
# Copyright (C) 2024 David Bauer <mail@david-bauer.net>

START=95
USE_PROCD=1

NAME=node-whisperer
PROG=/usr/bin/gluon-diagnostic

. /lib/functions.sh

reload_service() {
	restart_service
}

service_triggers() {
	procd_add_reload_trigger node-whisperer
}

start_service()
{
	ENABLED="$(uci -q get node-whisperer.settings.enabled)"
	ENABLED="${ENABLED:-1}"

	[ "$ENABLED" -gt 0 ] || return

	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}
